//
// Copyright 2024 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//

// WARNING: THIS FILE IS GENERATED BY usdGenSchema.  DO NOT EDIT.
TF_WRAP(WandelbotsNOVAMotionGroupAPI);
TF_WRAP(WandelbotsNOVAToolAPI);
TF_WRAP(WandelbotsNOVAGhostObjectAPI);
TF_WRAP(WandelbotsNOVAToolCenterPoint);
TF_WRAP(WandelbotsNOVASchemaTokens);
